/**
 * PT-PT keywords for complexity scoring dimensions.
 * 
 * Each dimension matches the English counterpart in complexity.ts.
 * Add more keywords per dimension as needed.
 */
export const PT_COMPLEXITY_KEYWORDS: Record<string, string[]> = {
  formalLogic: [
    'provar',
    'prova',
    'derivar',
    'derivação',
    'derivacao',
    'teorema',
    'lema',
    'corolário',
    'corolario',
    'axioma',
    'postulado',
    'inducao',
    'indução',
    'deducao',
    'dedução',
    'verificar formalmente',
    'satisfabilidade',
    'completude',
    'indecidivel',
    'indecidível',
    'conjetura',
    'conjectura',
    'hipotese',
    'hipótese',
  ],

  analyticalReasoning: [
    'comparar',
    'contrastar',
    'avaliar',
    'avaliação',
    'avaliacao',
    'analisar',
    'analise',
    'análise',
    'trade-offs',
    'prós e contras',
    'pros e contras',
    'vantagens e desvantagens',
    'pontos fortes e fracos',
    'implicacoes',
    'implicações',
    'ramificacoes',
    'ramificações',
    'por outro lado',
    'contra-argumento',
    'contraargumento',
    'nuance',
    'explicar',
    'explicação',
    'explicacao',
    'interpretar',
    'justificar',
  ],

  codeGeneration: [
    'implementar',
    'implementacao',
    'implementação',
    'criar uma funcao',
    'criar uma função',
    'criar uma classe',
    'construir um componente',
    'escrever código',
    'escrever codigo',
    'criar uma api',
    'criar um módulo',
    'criar um modulo',
    'scaffold',
    'escrever um teste',
    'gerar código',
    'gerar codigo',
    'componente',
    'endpoint',
    'handler',
    'controlador',
    'funcao',
    'função',
    'metodo',
    'método',
    'classe',
    'variavel',
    'variável',
    'array',
    'objeto',
    'objecto',
    'loop',
    'sintaxe',
    'compilar',
    'runtime',
    'parse',
    'analisar',
    'importar',
    'exportar',
    'modulo',
    'módulo',
    'async',
    'await',
    'callback',
    'promise',
    'promessa',
    'retornar',
    'parametro',
    'parâmetro',
    'argumento',
    'codigo',
    'codigo',
    'script',
    'consola',
    'console',
    'imprimir',
    'string',
    'inteiro',
    'boolean',
    'booleano',
    'nulo',
    'tipo',
    'interface',
    'enum',
    'constante',
    'lambda',
    'para loop',
    'while',
    'if else',
    'se senao',
    'se não',
    'try catch',
    'tratamento de erros',
    'teste unitario',
    'teste unitário',
  ],

  codeReview: [
    'corrigir bug',
    'corrigir erro',
    'debug',
    'depurar',
    'porque falha',
    'rever código',
    'rever codigo',
    'revisão de código',
    'revisao de codigo',
    'code review',
    'refactor',
    'refatorar',
    'otimizar',
    'otimizar',
    'encontrar o erro',
    'stack trace',
    'excecao',
    'exceção',
    'exception',
    'segfault',
    'memory leak',
    'fuga de memoria',
    'fuga de memória',
    'race condition',
    'condicao de corrida',
    'condição de corrida',
    'deadlock',
    'off by one',
    'typeerror',
    'referenceerror',
    'syntaxerror',
    'vulnerabilidades',
    'vulnerabilidade',
  ],

  technicalTerms: [
    'algoritmo',
    'kubernetes',
    'distribuido',
    'distribuído',
    'microservico',
    'microserviço',
    'base de dados',
    'arquitetura',
    'arquitectura',
    'infraestrutura',
    'deploy',
    'implantar',
    'pipeline',
    'middleware',
    'encriptacao',
    'encriptação',
    'autenticacao',
    'autenticação',
    'autorizacao',
    'autorização',
    'latinencia',
    'latência',
    'throughput',
    'concorrencia',
    'concorrência',
    'paralelismo',
    'serializacao',
    'serialização',
    'react',
    'graphql',
    'typescript',
    'docker',
    'sql',
    'redis',
    'frontend',
    'backend',
    'servidor',
    'api',
    'oauth',
    'seguranca',
    'segurança',
    'python',
    'javascript',
    'java',
    'golang',
    'rust',
    'ruby',
    'swift',
    'kotlin',
    'php',
    'html',
    'css',
    'node.js',
    'nodejs',
    'nextjs',
    'vue',
    'angular',
    'svelte',
    'django',
    'flask',
    'fastapi',
    'express',
    'nestjs',
    'postgres',
    'mongodb',
    'webpack',
    'vite',
    'npm',
    'git',
    'cli',
    'json',
    'yaml',
    'regex',
    'rest',
    'soap',
    'graphql',
    'websocket',
    'ssl',
    'tls',
    'https',
  ],

  simpleIndicators: [
    'olá',
    'ola',
    'bom dia',
    'boa tarde',
    'boa noite',
    'obrigado',
    'obrigada',
    'obg',
    'sim',
    'não',
    'nao',
    'ok',
    'okay',
    'claro',
    'percebi',
    'entendi',
    'compreendi',
    'tudo bem',
    'como estás',
    'como estas',
    'por favor',
    'pf',
    'ajuda',
    'socorro',
    'tchau',
    'xau',
    'ate logo',
    'até logo',
    'what is',
    'define',
    'translate',
    'thanks',
    'thank you',
    'yes',
    'no',
    'sure',
    'got it',
    'hi',
    'hello',
    'hey',
    'bye',
    'goodbye',
    'how are you',
    'good morning',
    'good night',
    'please',
    'help',
    'what time',
    'where is',
    'who is',
  ],

  multiStep: [
    'primeiro',
    'depois',
    'em seguida',
    'finalmente',
    'passo 1',
    'passo 2',
    'passo 3',
    'fase 1',
    'fase 2',
    'etapa',
    'proximo',
    'próximo',
    'seguido de',
    'em sequencia',
    'em sequência',
    'sequencia',
    'sequência',
    'workflow',
    'fluxo de trabalho',
    'pipeline',
    'uma vez que',
    'subsequentemente',
    'planeamento',
    'planeamento',
    'plano de acao',
    'plano de ação',
    'estrategia',
    'estratégia',
    'metodologia',
  ],

  creative: [
    'historia',
    'história',
    'poema',
    'criativo',
    'brainstorm',
    'imaginar',
    'ficcao',
    'ficção',
    'narrativa',
    'personagem',
    'enredo',
    'dialogo',
    'diálogo',
    'compor',
    'composicao',
    'composição',
    'artistico',
    'artístico',
    'metafora',
    'metáfora',
    'alegoria',
    'conto',
    'romance',
    'verso',
    'letra de musica',
    'letra de música',
  ],

  questionComplexity: [
    'como e que x se relaciona com y',
    'qual a relacao entre',
    'qual a relação entre',
    'quais as implicacoes',
    'quais as implicações',
    'porque e que',
    'por que razao',
    'o que acontece se',
    'sob que condicoes',
    'sob que condições',
    'como abordarias',
    'qual a diferenca entre',
    'qual a diferença entre',
  ],

  imperativeVerbs: [
    'construir',
    'criar',
    'actualizar',
    'atualizar',
    'fazer deploy',
    'enviar',
    'verificar',
    'executar',
    'instalar',
    'configurar',
    'lancar',
    'lançar',
    'publicar',
    'submeter',
    'iniciar',
    'comecar',
    'começar',
    'parar',
    'reiniciar',
    'apagar',
    'remover',
    'eliminar',
    'rever',
    'revisar',
    'otimizar',
    'otimizar',
    'analisar',
    'escanear',
    'digitalizar',
    'gerir',
    'listar',
    'mostrar',
    'abrir',
    'fechar',
  ],

  outputFormat: [
    'como json',
    'em json',
    'como yaml',
    'em yaml',
    'como csv',
    'em csv',
    'markdown',
    'como tabela',
    'numa tabela',
    'como xml',
    'em xml',
    'formatado como',
    'devolver como',
    'retornar como',
    'no formato',
    'como lista',
    'em lista',
  ],

  domainSpecificity: [
    'p-value',
    'valor p',
    'intervalo de confianca',
    'intervalo de confiança',
    'regressao',
    'regressão',
    'hipaa',
    'gdpr',
    'rgpd',
    'sec filing',
    'tort',
    'responsabilidade civil',
    'fiduciario',
    'fiduciário',
    'amortizacao',
    'amortização',
    'eigenvalue',
    'autovalor',
    'fourier transform',
    'transformada de fourier',
    'bayesian',
    'bayesiano',
    'posteriori',
    'genoma',
    'fenotipo',
    'fenótipo',
    'farmacocinetica',
    'farmacocinética',
    'distribuicao',
    'distribuição',
    'probabilidade',
    'estatistica',
    'estatística',
    'calcular',
    'calculo',
    'cálculo',
  ],

  agenticTasks: [
    'triage',
    'triagem',
    'auditar',
    'auditoria',
    'investigar',
    'monitorar',
    'monitorizar',
    'orquestrar',
    'coordenar',
    'coordenacao',
    'coordenação',
    'agendar',
    'prioritizar',
    'priorizar',
    'delegar',
    'delegacao',
    'delegação',
    'processo batch',
    'batch',
    'examinar todos',
    'verificar todos',
    'rever todos',
    'atualizar todos',
    'actualizar todos',
    'migrar',
    'migracao',
    'migração',
    'remediacao',
    'remediação',
    'automatizar',
    'automatizacao',
    'automatização',
  ],

  relay: [
    'encaminhar para',
    'reencaminhar',
    'escalar',
    'transferir para',
    'passar para',
    'relay',
    'retransmitir',
    'apenas dizer',
    'diz-lhes',
    'diz-lhe',
    'envia isto para',
    'notificar',
    'notificacao',
    'notificação',
    'ping',
    'acknowledge',
    'confirmar rececao',
    'confirmar receção',
    'marcar como lido',
    'marcar como lida',
  ],
};
